name: pull-request-template
description: Template estruturado para criação de Pull Requests
title: "PR: Descrição curta da alteração"

body:
  - type: input
    id: issue
    attributes:
      label: "⭐ 1. Issue"
      description: "Insira o link da issue relacionada"
      placeholder: "https://github.com/orgs/AGX-Software/projects/XXXX"
    validations:
      required: true

  - type: textarea
    id: pull_requests_links
    attributes:
      label: "🔗 2. Pull Requests (Links)"
      description: "Links diretos para outros PRs relacionados (Front-end e Back-end)"
      value: |
        *Front-end*:

        *Back-end*:
    validations:
      required: false

  - type: textarea
    id: descricao
    attributes:
      label: "📋 3. Descrição"
      description: "Explique o que está sendo entregue neste PR"
      value: "n/a"
    validations:
      required: true

  - type: textarea
    id: notas_adicionais
    attributes:
      label: "ℹ️ 4. Notas adicionais importantes"
      description: "Inclua observações importantes sobre comportamento, riscos, validações, etc."
      value: "n/a"
    validations:
      required: false

  - type: textarea
    id: pre_deploy
    attributes:
      label: "🛠️ 5. Configurações pré-deploy"
      description: "Existe algum ajuste necessário antes de subir para produção?"
      value: "n/a"
    validations:
      required: false

  - type: checkboxes
    id: ordem_de_subida
    attributes:
      label: "⬆️ 6. Qual deve subir primeiro?"
      description: "Selecione a ordem de deploy necessária"
      options:
        - label: "Front-end"
        - label: "Back-end"
        - label: "Tem que ser ao mesmo tempo"
        - label: "Não irá quebrar independente da ordem"
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: "📷 7. Screenshots"
      description: "Adicione imagens ilustrando alterações, quando aplicável"
      value: "n/a"
    validations:
      required: false
