name: "Dívida Técnica"
description: "Dívida técnica, refatoração ou limpeza de código"
title: "[DEBT] "

body:
  - type: textarea
    id: motivation
    attributes:
      label: "💡 Motivação"
      description: "Por que esta dívida técnica é necessária? Qual problema ela resolve? Qual o contexto atual?"
      placeholder: |
        - Código difícil de manter ou entender.
        - Performance insatisfatória em determinada funcionalidade.
        - Riscos de bugs ou falhas devido à complexidade atual.
    validations:
      required: true

  - type: textarea
    id: objective
    attributes:
      label: "🎯 Objetivo"
      description: "Objetivo direto e mensurável desta funcionalidade."
      placeholder: |
        - Melhorar legibilidade do código.
        - Reduzir tempo de resposta de Xms para Yms.
        - Aumentar cobertura de testes em Z%.
    validations:
      required: true

  - type: textarea
    id: checklist
    attributes:
      label: "✅ Checklist"
      description: "Liste exatamente o que deve ser implementado."
      placeholder: |
        - [ ] Refatorar módulo X
        - [ ] Otimizar função Y
        - [ ] Adicionar testes para Z
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: "📋 Descrição Detalhada"
      description: "Explique o funcionamento, regras de negócio e fluxos principais."
      placeholder: |
        - Resumo da dívida técnica
        - Impactos atuais no sistema
        - Justificativa para a intervenção
    validations:
      required: true   

  - type: checkboxes
    id: technicalDebtType
    attributes:
      label: "📊 Tipo de Dívida Técnica"
      description: "Selecione o(s) tipo(s) aplicável(is)."
      options:
        - label: "Refatoração de código"
        - label: "Melhoria de performance"
        - label: "Melhoria de legibilidade"
        - label: "Remoção de duplicação"
        - label: "Aumento de testabilidade"
        - label: "Atualização de dependências"
        - label: "Adequação de arquitetura"
        - label: "Outro (descrever abaixo)"
    validations:
      required: true

  - type: textarea
    id: otherDebtType
    attributes:
      label: "📌 Outro tipo de dívida (se selecionado)"
      placeholder: "Descreva aqui se escolheu 'Outro'"
    validations:
      required: false

  - type: dropdown
    id: benefit
    attributes:
      label: "📈 Benefício Esperado"
      description: "O impacto positivo após resolver esta dívida."
      options:
        - Baixo (Melhorias incrementais, impacto limitado)
        - Médio (Melhorias notáveis, mas não críticas)
        - Alto (Melhoria significativa na manutenção, performance ou segurança)
    validations:
      required: true

  - type: dropdown
    id: initialEstimate
    attributes:
      label: "🗓️ Estimativa Inicial"
      description: "Tempo aproximado para conclusão."
      options:
        - Menos de 1 dia
        - 1-3 dias
        - 4-7 dias
        - 1-2 semanas
        - Mais de 2 semanas
    validations:
      required: true

  - type: textarea
    id: risksAndConsiderations
    attributes:
      label: "⚠️ Riscos & Considerações"
      description: "O que pode dar errado? O que deve ser observado?"
      placeholder: |
        - Possíveis regressões
        - Componentes afetados
        - Dependências internas ou externas
        - Mudanças que podem impactar outros fluxos
    validations:
      required: false

  - type: textarea
    id: proposedSolution
    attributes:
      label: "✨ Solução Proposta"
      description: "Explique a estratégia para resolver a dívida técnica."
      placeholder: |
        - Extrair lógica duplicada para um serviço unificado.
        - Reescrever módulo utilizando padrão X.
        - Atualizar dependência Y para versão mais recente.
    validations:
      required: false

  - type: textarea
    id: evidences
    attributes:
      label: "📷 Evidências"
      description: "Anexe qualquer evidência que ajude a ilustrar o problema."
      placeholder: |
        - Screenshots
        - Trechos de logs
        - Vídeos demonstrativos
        - Requisições HTTP utilizadas na reprodução (ex.: curl)
    validations:
      required: false

  - type: textarea
    id: additionalInformation
    attributes:
      label: "📝 Informações Adicionais"
      description: "Contexto extra ou informações úteis para o time."
      placeholder: "Adicione detalhes relevantes que não se encaixam nos campos anteriores."
    validations:
      required: false

