name: debtYAML
description: Dívida técnica, refatoração ou limpeza de código
title: "Debt: Descrição clara do trabalho técnico"

body:
  - type: textarea
    id: motivation
    attributes:
      label: 🎯 Motivação
      description: Por que este trabalho técnico é necessário? Qual é o impacto de não fazer isso?
    validations:
      required: true

  # - type: checkboxes
  #   id: typeOfTechnicalDebt
  #   attributes:
  #     label: 📊 Tipo de Dívida Técnica
  #     options:
  #       - label: "Refatoração de código"
  #       - label: "Melhoria de performance"
  #       - label: "Melhoria de legibilidade"
  #       - label: "Remoção de código duplicado"
  #       - label: "Atualização de dependências"
  #       - label: "Outro: ___________"
  #   validations:
  #     required: true
  
  - type: dropdown
    id: benefit
    attributes:
      label: Benefício
      options:
        - Alto
        - Médio
        - Baixo
    validations:
      required: true
  
  - type: dropdown
    id: effort
    attributes:
      label: Esforço
      options:
        - Alto
        - Médio
        - Baixo
    validations:
      required: true

  - type: textarea
    id: problemDescription
    attributes:
      label: 📝 Descrição do Problema
      description: Descreva o código ou comportamento atual que precisa ser melhorado.
    validations:
      required: true

  - type: textarea
    id: proposedSolution
    attributes:
      label: ✨ Solução Proposta
      description: Descreva a abordagem para resolver este problema técnico.
    validations:
      required: true

  - type: textarea
    id: expectedImpact
    attributes:
      label: 📊 Impacto Esperado
      description: Descreva a abordagem para resolver este problema técnico.
      value: |
      - **Performance**: [Ex: Ganho de ~Xms por validação, já que será centralizada em um serviço único (menos re-cálculos)]
      - **Manutenibilidade**: [Ex: Código fica 80% mais legível, facilita adicionar novas validações (CEP, CNPJ) no futuro]
      - **Segurança**: [Ex: Centralizar validação reduz risco de brechas de segurança na implementação de X]
    validations:
      required: true

  - type: textarea
    id: risksAndConsiderations
    attributes:
      label: ⚠️ Riscos e Considerações
      value: |
      - Possíveis regressões: [descrever]
      - Componentes afetados: [listar]
      - Dependências: [listar]
    validations:
      required: true

  - type: textarea
    id: codeAndRelevantFiles
    attributes:
      label: 🔗 Código e Arquivos Relevantes
      value: |
      - Arquivo 1: [caminho]
      - Arquivo 2: [caminho]
      - Arquivo 3: [caminho]
    validations:
      required: true

  - type: textarea
    id: acceptanceCriteria
    attributes:
      label: ✅ Critérios de Aceição
      value: |
      - [ ] Código refatorado conforme específicação
      - [ ] Testes existentes continuam passando
      - [ ] Novos testes adicionados (se necessário)
      - [ ] Sem regressões
      - [ ] Code review aprovado
      - [ ] Documentação atualizada (se aplicável)
      - [ ] Deploy seguro validado
    validations:
      required: true

  - type: textarea
    id: acceptanceCriteria
    attributes:
      label: ✅ Critérios de Aceição
      value: |
      - [ ] Código refatorado conforme específicação
      - [ ] Testes existentes continuam passando
      - [ ] Novos testes adicionados (se necessário)
      - [ ] Sem regressões
      - [ ] Code review aprovado
      - [ ] Documentação atualizada (se aplicável)
      - [ ] Deploy seguro validado
    validations:
      required: true

  - type: textarea
    id: estimatedTime
    attributes:
      label: 📅 Estimativa de Tempo
      value: |
      Tempo estimado: [ex: 8 horas / 2 dias]
    validations:
      required: true

  - type: textarea
    id: additionalNotes
    attributes:
      label: 📝 Observações Adicionais
      value: [Contexto adicional que possa ser útil]
    validations:
      required: true