name: "Dívida Técnica"
description: "Dívida técnica, refatoração ou limpeza de código"
title: "[DEBT]"

body:
  - type: textarea
    id: motivation
    attributes:
      label: "💡 Motivação"
      description: "Por que esta dívida técnica é necessária? Qual problema ela resolve? Qual o contexto atual?"
      placeholder: |
        - Código difícil de manter ou entender.
        - Performance insatisfatória em determinada funcionalidade.
        - Riscos de bugs ou falhas devido à complexidade atual.
    validations:
      required: true

  - type: textarea
    id: objective
    attributes:
      label: "🎯 Objetivo"
      description: "Objetivo direto e mensurável desta funcionalidade."
      placeholder: |
        - Melhorar legibilidade do código.
        - Reduzir tempo de resposta de Xms para Yms.
        - Aumentar cobertura de testes em Z%.
    validations:
      required: true

  - type: textarea
    id: checklist
    attributes:
      label: "✅ Checklist"
      description: "Liste exatamente o que deve ser implementado."
      placeholder: |
        - [ ] Refatorar módulo X
        - [ ] Otimizar função Y
        - [ ] Adicionar testes para Z
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: "📋 Descrição Detalhada"
      description: "Explique o funcionamento, regras de negócio e fluxos principais."
      placeholder: |
        - Resumo da dívida técnica
        - Impactos atuais no sistema
        - Justificativa para a intervenção
    validations:
      required: true   

  - type: checkboxes
    id: technicalDebtType
    attributes:
      label: "📊 Tipo de Dívida Técnica"
      description: "Selecione o(s) tipo(s) aplicável(is)."
      options:
        - label: "Refatoração de código"
        - label: "Melhoria de performance"
        - label: "Melhoria de legibilidade"
        - label: "Remoção de duplicação"
        - label: "Aumento de testabilidade"
        - label: "Atualização de dependências"
        - label: "Adequação de arquitetura"
        - label: "Outro (descrever abaixo)"
    validations:
      required: true

  - type: textarea
    id: otherDebtType
    attributes:
      label: "📌 Outro tipo de dívida (se selecionado)"
      placeholder: "Descreva aqui se escolheu 'Outro'"
    validations:
      required: false

  - type: dropdown
    id: benefit
    attributes:
      label: "📈 Benefício Esperado"
      description: "O impacto positivo após resolver esta dívida."
      options:
        - Alto (Melhoria significativa na manutenção, performance ou segurança)
        - Médio (Melhorias notáveis, mas não críticas)
        - Baixo (Melhorias incrementais, impacto limitado)
    validations:
      required: true

  - type: dropdown
    id: effort
    attributes:
      label: "⏳ Esforço Estimado"
      description: "Complexidade e tempo aproximado."
      options:
        - Alto (Complexidade alta, muitas mudanças necessárias)
        - Médio (Complexidade moderada, algumas mudanças necessárias)
        - Baixo (Simples, poucas mudanças necessárias)
    validations:
      required: true

  - type: textarea
    id: risksAndConsiderations
    attributes:
      label: "⚠️ Riscos & Considerações"
      description: "O que pode dar errado? O que deve ser observado?"
      placeholder: |
        - Possíveis regressões
        - Componentes afetados
        - Dependências internas ou externas
        - Mudanças que podem impactar outros fluxos
    validations:
      required: false

  - type: textarea
    id: proposedSolution
    attributes:
      label: "✨ Solução Proposta"
      description: "Explique a estratégia para resolver a dívida técnica."
      placeholder: |
        - Extrair lógica duplicada para um serviço unificado.
        - Reescrever módulo utilizando padrão X.
        - Atualizar dependência Y para versão mais recente.
    validations:
      required: false

  - type: textarea
    id: designAndReferences
    attributes:
      label: "🎨 Design & Referências"
      description: "Inclua material visual e referências importantes."
      placeholder: |
        - Links para designs no Figma
        - Links para diagramas relevantes
        - Screenshots de referência
        - Documentação relevante
    validations:
      required: false

  - type: textarea
    id: technicalDetails
    attributes:
      label: "🛠️ Detalhes Técnicos"
      description: "Informações técnicas relevantes para implementação."
      placeholder: |
        - Componentes que serão afetados
        - Mudanças necessárias na API
        - Serviços/contexts envolvidos
        - Possíveis impactos no versionamento
    validations:
      required: false

  - type: textarea
    id: additionalInformation
    attributes:
      label: "📝 Informações Adicionais"
      description: "Contexto extra ou informações úteis para o time."
      placeholder: "Adicione detalhes relevantes que não se encaixam nos campos anteriores."
    validations:
      required: false

