name: "Nova Funcionalidade"
description: "Implementação de nova funcionalidade"
title: "[FEATURE] "

body:
  - type: textarea
    id: motivation
    attributes:
      label: "💡 Motivação"
      description: "Por que esta feature é necessária? Qual problema ela resolve? Qual o contexto atual?"
      placeholder: |
        - Usuários não conseguem visualizar X, dificultando Y.
        - Processo atual é manual e causa erros em Z.
        - Necessário para habilitar o fluxo ABC.
    validations:
      required: true

  - type: textarea
    id: objective
    attributes:
      label: "🎯 Objetivo"
      description: "Objetivo direto e mensurável desta funcionalidade."
      placeholder: |
        - Permitir consulta em tempo real.
        - Reduzir tempo do fluxo de 5 para 2 passos.
        - Criar base técnica para recurso futuro XYZ.
    validations:
      required: true

  - type: textarea
    id: checklist
    attributes:
      label: "✅ Checklist"
      description: "Liste exatamente o que deve ser implementado."
      placeholder: |
        - [ ] Criar endpoint X
        - [ ] Implementar tela Y
        - [ ] Ajustar fluxo Z
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: "📋 Descrição Detalhada"
      description: "Explique o funcionamento, regras de negócio e fluxos principais."
      placeholder: |
        - Resumo da funcionalidade
        - Regras de negócio
        - Validações importantes
        - Fluxo do usuário
    validations:
      required: true

  - type: textarea
    id: designAndReferences
    attributes:
      label: "🎨 Design & Referências"
      description: "Inclua material visual e referências importantes."
      placeholder: |
        - https://www.figma.com/design/1234
        - Protótipo interativo (modo apresentação)
        - https://www.drawio.com/example-diagrams
        - Screenshots de referência
        - Documentação relevante
    validations:
      required: false

  - type: textarea
    id: technicalDetails
    attributes:
      label: "🛠️ Detalhes Técnicos"
      description: "Informações técnicas relevantes para implementação."
      placeholder: |
          - Requisições HTTP utilizadas na reprodução (ex.: curl)
          - Logs do servidor ou console
          - Arquivos de configuração relevantes
          - Versões de software envolvidas
    validations:
      required: false

  - type: textarea
    id: additionalInformation
    attributes:
      label: "📝 Informações Adicionais"
      description: "Contexto extra ou informações úteis para o time."
      placeholder: "Adicione detalhes relevantes que não se encaixam nos campos anteriores."
    validations:
      required: false