name: feature
description: Implementação de nova funcionalidade
title: ""

body:
  - type: textarea
    id: motivation
    attributes:
      label: "💡 1. Motivação"
      description: "Por que esta feature é necessária? Qual dor do usuário resolve? Qual impacto traz para o produto?"
      placeholder: |
        Exemplos:
        - Usuários não conseguem visualizar X, dificultando Y.
        - Processo atual é manual e causa erros em Z.
        - Feature necessária para habilitar fluxo ABC.
    validations:
      required: true

  - type: textarea
    id: objective
    attributes:
      label: "🎯 2. Objetivo"
      description: "Objetivo direto e mensurável desta funcionalidade."
      placeholder: |
        Exemplos:
        - Permitir que usuários consultem informações em tempo real.
        - Reduzir o tempo do fluxo atual de 5 para 2 passos.
        - Criar base técnica para feature futura XYZ.
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: "📋 3. Descrição Detalhada"
      description: "Explique o funcionamento da feature, fluxos principais e comportamento esperado."
      placeholder: |
        Incluir:
        - Resumo geral da funcionalidade
        - Regras de negócio
        - Eventos importantes (ex: validações, triggers)
        - Como o usuário inicia e finaliza o fluxo
    validations:
      required: true

  - type: textarea
    id: scope
    attributes:
      label: "🧭 4. Escopo"
      description: "Liste exatamente o que faz parte deste desenvolvimento e o que não faz."
      placeholder: |
        **Incluso nesta entrega:**
        - [ ] Item 1 — Ex: Cálculo de simulação com múltiplos prazos
        - [ ] Item 2 — Ex: Histórico local de simulações
        - [ ] Item 3 — Ex: Validação de CPF no formulário
    validations:
      required: false

  - type: textarea
    id: affected_users
    attributes:
      label: "👥 5. Usuários Afetados"
      description: "Quem utilizará esta feature? Como será afetado?"
      placeholder: |
        Exemplos:
        - Perfil Administrador: poderá acessar painel com métricas avançadas.
        - Cliente final: verá nova opção de pagamento.
    validations:
      required: false

  - type: textarea
    id: design_references
    attributes:
      label: "🎨 6. Design e Recursos Visuais"
      description: "Inclua links, anexos e fluxos considerados."
      placeholder: |
        ### Figma
        [Link do design no Figma]

        ### Fluxo de Usuário
        - Descrever fluxo
        - Anexar ou linkar diagrama (opcional)

        ### Observações de UX
        - Regras, microinterações, validações visuais
    validations:
      required: false

  - type: textarea
    id: implementation_details
    attributes:
      label: "🛠️ 7. Detalhes de Implementação"
      description: "Informações técnicas úteis para desenvolvimento."
      value: |
        ### Arquitetura
        - Descrever mudanças necessárias (ex: novos endpoints, camadas, padrões)

        ### Componentes Afetados
        - Lista dos arquivos, páginas, módulos ou serviços alterados

        ### Dependências
        - APIs, libs, serviços internos

        ### Considerações Técnicas
        - Performance
        - Segurança
        - Compatibilidade
        - Feature flags (se aplicável)
    validations:
      required: true

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: "✅ 8. Critérios de Aceitação"
      description: "O que precisa acontecer para esta feature ser considerada pronta?"
      placeholder: |
        - [ ] Feature implementada conforme especificação
        - [ ] Comportamentos revisados junto ao Product Owner
        - [ ] Sem regressões
        - [ ] Documentação atualizada (ex: wiki, readme)
        - [ ] Code review aprovado
        - [ ] Testada nos navegadores suportados (Chrome, Firefox, Safari, Edge)
        - [ ] Pronta para produção
    validations:
      required: true

  - type: textarea
    id: references_context
    attributes:
      label: "🔗 10. Referências e Contexto Adicional"
      placeholder: |
        - Links de issues relacionadas
        - Documentação
        - Discussões anteriores
        - Reuniões / decisões de produto
    validations:
      required: false

  - type: textarea
    id: additional_notes
    attributes:
      label: "📝 11. Observações Adicionais"
      placeholder: "Qualquer informação adicional relevante"
    validations:
      required: false
