name: "Nova Funcionalidade"
description: "Implementação de nova funcionalidade"
title: "[FEATURE] "

body:
  - type: textarea
    id: motivation
    attributes:
      label: "💡 Motivação"
      description: "Por que esta feature é necessária? Qual dor do usuário resolve? Qual impacto traz para o produto?"
      placeholder: |
        Exemplos:
        - Usuários não conseguem visualizar X, dificultando Y.
        - Processo atual é manual e causa erros em Z.
        - Feature necessária para habilitar fluxo ABC.
    validations:
      required: true

  - type: textarea
    id: objective
    attributes:
      label: "🎯 Objetivo"
      description: "Objetivo direto e mensurável desta funcionalidade."
      placeholder: |
        Exemplos:
        - Permitir que usuários consultem informações em tempo real.
        - Reduzir o tempo do fluxo atual de 5 para 2 passos.
        - Criar base técnica para feature futura XYZ.
    validations:
      required: true

  - type: textarea
    id: scope
    attributes:
      label: "🧭 Escopo"
      description: "Liste exatamente o que faz parte deste desenvolvimento."
      value: "- [ ] "
      placeholder: |
        Itens inclusos:
        - [ ] Ex: Cálculo de simulação com múltiplos prazos
        - [ ] Ex: Histórico local de simulações
        - [ ] Ex: Validação no formulário
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: "📋 Descrição Detalhada"
      description: "Explique o funcionamento da feature, fluxos principais e comportamento esperado."
      placeholder: |
        Incluir:
        - Resumo geral da funcionalidade
        - Regras de negócio
        - Eventos ou validações importantes
        - Como o usuário inicia e finaliza o fluxo
    validations:
      required: true

  - type: textarea
    id: affected_users
    attributes:
      label: "👥 Usuários Afetados"
      description: "Quem utilizará esta feature? Como será afetado?"
      placeholder: |
        Exemplos:
        - Administradores terão acesso a X
        - Clientes finais verão nova opção Y
    validations:
      required: false

  - type: textarea
    id: design_references
    attributes:
      label: "🎨 Design e Recursos Visuais"
      description: "Inclua links ou anexos de design, fluxos e referências."
      placeholder: |
        Exemplos:
        - Link do Figma
        - Fluxo do usuário
        - Regras de UX ou validações visuais
    validations:
      required: false

  - type: textarea
    id: implementation_details
    attributes:
      label: "🛠️ Detalhes de Implementação"
      description: "Informações técnicas úteis para desenvolvimento."
      placeholder: |
        Arquitetura:
        - Descrever mudanças necessárias (novos endpoints, camadas, padrões)

        Componentes Afetados:
        - Listar arquivos, páginas, módulos ou serviços alterados

        Dependências:
        - APIs, libs, serviços internos

        Considerações Técnicas:
        - Performance
        - Segurança
        - Compatibilidade
        - Feature flags (se aplicável)
    validations:
      required: true

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: "✅ Critérios de Aceitação"
      description: "O que precisa acontecer para esta feature ser considerada pronta?"
      placeholder: |
        - [ ] Feature implementada conforme especificação
        - [ ] Comportamentos revisados com o Product Owner
        - [ ] Sem regressões
        - [ ] Documentação atualizada
        - [ ] Code review aprovado
        - [ ] Testado nos navegadores suportados
        - [ ] Pronto para produção
    validations:
      required: true

  - type: textarea
    id: references_context
    attributes:
      label: "🔗 Referências e Contexto Adicional"
      placeholder: |
        Exemplos:
        - Links para issues relacionadas
        - Documentações relevantes
        - Discussões anteriores
        - Notas de reuniões
    validations:
      required: false

  - type: textarea
    id: additional_notes
    attributes:
      label: "📝 Observações Adicionais"
      placeholder: "Qualquer informação complementar relevante."
    validations:
      required: false
