name: "Melhoria"
description: "Melhoria de uma funcionalidade existente"
title: "[IMPROVEMENT] "

body:
  - type: textarea
    id: motivation
    attributes:
      label: "💡 Motivação"
      description: "Por que esta melhoria é necessária? Qual problema ela resolve? Qual o contexto atual?"
      placeholder: |
        - Processo atual é lento ou confuso para o usuário.
        - Existem reclamações frequentes relacionadas ao fluxo X.
        - Melhorias necessárias para aumentar performance, UX ou segurança.
    validations:
      required: true

  - type: textarea
    id: objective
    attributes:
      label: "🎯 Objetivo"
      description: "Objetivo direto e mensurável desta funcionalidade."
      placeholder: |
        - Reduzir tempo de carregamento de 100ms para 30ms.
        - Tornar o fluxo mais intuitivo para o usuário.
        - Diminuir quantidade de erros no processo atual.
    validations:
      required: true

  - type: textarea
    id: checklist
    attributes:
      label: "✅ Checklist"
      description: "Liste exatamente o que deve ser implementado."
      placeholder: |
        - [ ] Criar endpoint X
        - [ ] Implementar tela Y
        - [ ] Ajustar fluxo Z
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: "📋 Descrição Detalhada"
      description: "Explique o funcionamento, regras de negócio e fluxos principais."
      placeholder: |
        - Resumo da funcionalidade
        - Regras de negócio
        - Validações importantes
        - Fluxo do usuário
    validations:
      required: true      

  - type: textarea
    id: currentBehavior
    attributes:
      label: "🔄 Comportamento Atual"
      description: "Explique como a funcionalidade funciona hoje."
      placeholder: |
        - Descrição objetiva do fluxo atual
        - Prints se necessário
        - Problemas identificados no comportamento atual
    validations:
      required: true

  - type: textarea
    id: expectedBehavior
    attributes:
      label: "✨ Comportamento Após a Melhoria"
      description: "Descreva como a funcionalidade deve se comportar depois da correção/otimização."
      placeholder: |
        - Quais passos serão alterados
        - Como ficará a interação do usuário
        - Regras modificadas ou removidas
    validations:
      required: true

  - type: checkboxes
    id: expectedImpact
    attributes:
      label: "📊 Impacto Esperado"
      description: "Quais ganhos são esperados após aplicar a melhoria?"
      options:
        - label: "Melhoria de performance"
        - label: "Melhoria de usabilidade/UX"
        - label: "Redução de erros/falhas"
        - label: "Aumento de segurança"
        - label: "Redução de custos"
        - label: "Outro (descrever abaixo)"
    validations:
      required: true

  - type: input
    id: otherImpact
    attributes:
      label: "📌 Outro impacto (se selecionado)"
      description: "Descreva aqui se escolheu 'Outro'"
    validations:
      required: false

  - type: textarea
    id: designAndReferences
    attributes:
      label: "🎨 Design & Referências"
      description: "Inclua material visual e referências importantes."
      placeholder: |
        - Links para designs no Figma
        - Links para diagramas relevantes
        - Screenshots de referência
        - Documentação relevante
    validations:
      required: false

  - type: textarea
    id: technicalDetails
    attributes:
      label: "🛠️ Detalhes Técnicos"
      description: "Informações técnicas relevantes para implementação."
      placeholder: |
        - Componentes que serão afetados
        - Mudanças necessárias na API
        - Serviços/contexts envolvidos
        - Possíveis impactos no versionamento
    validations:
      required: false

  - type: textarea
    id: additionalInformation
    attributes:
      label: "📝 Informações Adicionais"
      description: "Contexto extra ou informações úteis para o time."
      placeholder: "Adicione detalhes relevantes que não se encaixam nos campos anteriores."
    validations:
      required: false
