name: "Melhoria"
description: "Melhoria de uma funcionalidade existente"
title: "[Melhoria] "

body:
  - type: textarea
    id: motivation
    attributes:
      label: "💡 Motivação"
      description: "Por que esta melhoria é necessária? Qual problema ela resolve? Qual o contexto atual?"
      placeholder: |
        Exemplos:
        - Processo atual é lento ou confuso para o usuário.
        - Existem reclamações frequentes relacionadas ao fluxo X.
        - Melhorias necessárias para aumentar performance, UX ou segurança.
    validations:
      required: true

  - type: textarea
    id: objective
    attributes:
      label: "🎯 Objetivo"
      description: "O que se deseja atingir com esta melhoria?"
      placeholder: |
        Exemplos:
        - Reduzir tempo de carregamento de 100ms para 30ms.
        - Tornar o fluxo mais intuitivo para o usuário.
        - Diminuir quantidade de erros no processo atual.
    validations:
      required: true

  - type: textarea
    id: expectedImpact
    attributes:
      label: "📊 Impacto Esperado"
      description: "Quais ganhos são esperados após aplicar a melhoria?"
      placeholder: |
        Exemplos:
        - **Performance:** Redução de X% no tempo de carregamento.
        - **UX:** Navegação mais fluida, menos passos, menos cliques.
        - **Técnico:** Redução de complexidade, menor carga no servidor.
        - **Negócio:** Aumento na conversão, maior retenção, menos chamados.
    validations:
      required: true

  - type: textarea
    id: currentBehavior
    attributes:
      label: "🔄 Comportamento Atual"
      description: "Explique como a funcionalidade funciona hoje."
      placeholder: |
        Inclua:
        - Descrição objetiva do fluxo atual
        - Prints se necessário
        - Problemas identificados no comportamento atual
    validations:
      required: true

  - type: textarea
    id: expectedBehavior
    attributes:
      label: "✨ Comportamento Após a Melhoria"
      description: "Descreva como a funcionalidade deve se comportar depois da correção/otimização."
      placeholder: |
        Inclua:
        - Quais passos serão alterados
        - Como ficará a interação do usuário
        - Regras modificadas ou removidas
    validations:
      required: true

  - type: textarea
    id: designAndReferences
    attributes:
      label: "🎨 Design & Referências"
      description: "Inclua material visual e referências importantes."
      placeholder: |
        ### Screenshots Atual
        [Adicionar capturas do comportamento atual aqui]

        ### Figma / Mockups
        [Link para o design atualizado]

        ### Benchmarks / Inspirações
        [Links externos, referências de UX, etc.]
    validations:
      required: false

  - type: textarea
    id: technicalDetails
    attributes:
      label: "🛠️ Detalhes Técnicos"
      description: "Informações técnicas relevantes para implementação."
      placeholder: |
        Exemplos:
        - Componentes que serão afetados
        - Mudanças necessárias na API
        - Serviços/contexts envolvidos
        - Possíveis impactos no versionamento
    validations:
      required: false

  - type: textarea
    id: additionalInformation
    attributes:
      label: "📝 Informações Adicionais"
      description: "Contexto extra ou informações úteis para o time."
      placeholder: "Adicione detalhes relevantes que não se encaixam nos campos anteriores."
    validations:
      required: false
